apiVersion: v1
kind: PersistentVolume
metadata:
  name: lldap-pv-data
  labels:
    type: local
spec:
  storageClassName: lldap-test-data
  accessModes:   
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/Volumes/workspaces/jeremy.mcmillan/workspace/lldap-data"